"""
plot.py — Visualization of the fall toward the Schwarzschild horizon
=====================================================================

Reads trajectory.csv generated by the C++ program and produces 4 plots:

  Fig 1 — Orbit in the (x, y) plane in Cartesian coordinates
  Fig 2 — Radial evolution r(τ) with horizon position
  Fig 3 — Effective potential Veff(r) + energy level E
  Fig 4 — Radial velocity ṙ(τ)

Dependencies: pandas, matplotlib, numpy
  pip install pandas matplotlib numpy
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import os
from matplotlib.collections import LineCollection

CSV_FILE = os.path.join(os.path.dirname(__file__), "../trajectory.csv")

# ── Physical parameters (must match params.h) ─────────────────
M  = 1.0
RS = 2.0 * M   # Schwarzschild radius
L  = 3.46
E  = 0.96


# ════════════════════════════════════════════════════════════════
#  Read CSV
# ════════════════════════════════════════════════════════════════

#   Load trajectory.csv into a pandas DataFrame.
#   First line is the header (columns: tau,r,phi,x,y_cart,Veff,rdot).

df = pd.read_csv(CSV_FILE, sep=',', skipinitialspace=True)
df.columns = df.columns.str.strip()
print(df.columns.tolist())


# Quick check
print(f"  {len(df)} points loaded")
print(df.head(3))


# ════════════════════════════════════════════════════════════════
#  General layout
# ════════════════════════════════════════════════════════════════

fig, axes = plt.subplots(2, 2, figsize=(13, 10))
fig.suptitle(
    f"Fall toward the Schwarzschild event horizon\n"
    f"M={M}  L={L}  E={E}  $r_s$={RS}",
    fontsize=13
)
ax_orbit, ax_r, ax_veff, ax_rdot = axes.flatten()


# ════════════════════════════════════════════════════════════════
#  Fig 1 — Orbit (x, y)
# ════════════════════════════════════════════════════════════════

ax = ax_orbit

#  Plot the trajectory (x, y_cart) with a color that evolves
#  along the trajectory to indicate progression.

sc = ax.scatter(df["x"], df["y_cart"], c=df["tau"], cmap="plasma", s=0.5)
fig.colorbar(sc, ax=ax, label="τ (proper time)")


# Schwarzschild horizon (circle of radius rs)
# Draw a black disk of radius RS centered at (0, 0).

horizon = patches.Circle((0, 0), RS, color='black', zorder=5)
ax.add_patch(horizon)


ax.set_aspect("equal")
ax.set_xlabel("x  [M]")
ax.set_ylabel("y  [M]")
ax.set_title("Orbit in the equatorial plane")
ax.grid(True, alpha=0.3)


# ════════════════════════════════════════════════════════════════
#  Fig 2 — Radial evolution r(τ)
# ════════════════════════════════════════════════════════════════

ax = ax_r

#   Plot r as a function of tau.
#   Add a red dashed horizontal line at r = RS (Schwarzschild horizon).

ax.plot(df["tau"], df["r"], color="steelblue", lw=1)
ax.axhline(RS, color="red", linestyle="--", label="horizon $r_s$")
ax.annotate("horizon $r_s$", xy=(df["tau"].iloc[0], RS),
            xytext=(0, 6), textcoords="offset points", color="red")
ax.legend()


ax.set_xlabel("τ  (proper time)")
ax.set_ylabel("r  [M]")
ax.set_title("Radial evolution")
ax.grid(True, alpha=0.3)


# ════════════════════════════════════════════════════════════════
#  Fig 3 — Effective potential Veff(r)
# ════════════════════════════════════════════════════════════════
#
#  Veff(r) is recomputed analytically on a fine grid,
#  independently of the simulation.
#
#  V²eff(r) = (1 - 2M/r)(1 + L²/r²)

ax = ax_veff

r_grid = np.linspace(RS + 0.1, 30.0, 800)

#   Compute Veff on r_grid

veff_grid = np.sqrt((1 - 2*M/r_grid) * (1 + L**2/r_grid**2))

#   Plot Veff(r) and add:
#   - a horizontal line E = const  (particle energy level)
#   - a grey shaded region for r < RS (inside the horizon)
#   - lightly hatched "forbidden" regions (E < Veff)

ax.plot(r_grid, veff_grid, color="darkorange", lw=2, label="$V_{eff}(r)$")
ax.axhline(E, color="steelblue", linestyle="--", label=f"E = {E}")
ax.axvspan(0, RS, color="black", alpha=0.3, label="horizon")
ax.fill_between(r_grid, veff_grid, E, where=(veff_grid > E),
                alpha=0.15, color="red", label="forbidden region")


ax.set_xlim(0, 25)
ax.set_xlabel("r  [M]")
ax.set_ylabel("$V_{\\mathrm{eff}}(r)$")
ax.set_title("Effective potential")
ax.legend()
ax.grid(True, alpha=0.3)


# ════════════════════════════════════════════════════════════════
#  Fig 4 — Radial velocity ṙ(τ)
# ════════════════════════════════════════════════════════════════

ax = ax_rdot

# Plot rdot (= dr/dτ) as a function of tau.
#   Add a horizontal line at 0 to identify turning points.

ax.plot(df["tau"], df["rdot"], color="mediumpurple", lw=1)
ax.axhline(0, color="gray", linestyle="--", lw=0.8)


ax.set_xlabel("τ  (proper time)")
ax.set_ylabel("dr/dτ")
ax.set_title("Radial velocity")
ax.grid(True, alpha=0.3)


# ════════════════════════════════════════════════════════════════
#  Display
# ════════════════════════════════════════════════════════════════

plt.tight_layout()
plt.savefig("schwarzschild_plots.png", dpi=150)
print("\n  → schwarzschild_plots.png saved")
plt.show()